# Generated by Django 5.1 on 2024-11-08 13:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='autho_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=998, unique=True),
            preserve_default=False,
        ),
    ]
