# Generated by Django 5.1 on 2024-11-08 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_author_autho_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='autho_id',
            new_name='author_id',
        ),
    ]
