# Generated by Django 5.1.3 on 2024-11-29 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_autho_id_author_author_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='author_id',
        ),
    ]
